# Twitter API credentials
API_KEY = "YOUR_API_KEY_HERE"
API_SECRET_KEY = "YOUR_API_SECRET_KEY_HERE"
ACCESS_TOKEN = "YOUR_ACCESS_TOKEN_HERE"
ACCESS_TOKEN_SECRET = "YOUR_ACCESS_TOKEN_SECRET_HERE"

# Other configuration parameters
TIMEZONE = "Asia/Kuala_Lumpur"
ZONE = "PHG02"
